### ISSUE TITLE
Incoming call notifications

### ISSUE THREAD

**Issue by jb55** [jb55/phonectl#1]
Need to figure out what's the best way to do this. Perhaps clients can just connect to the socket with a special command, waiting for specific events...

**Comment by norrinr** [comment]
If XMPP is too antiquated, how about matrix.org? with ability to log into private/self-hosted matrix-synapse server, of course.

**Comment by jb55** [comment]
oh this is already solved by gtalksms recently, you need to turn on accessibility and then it will send all notifications over xmpp
